### ISSUE TITLE
Field "overall_average_fuel_consumption" of type float is missing in TripStatistics instance

### ISSUE THREAD

**Issue by equareo** [skodaconnect/homeassistant-myskoda#104]
2024-10-17 20:56:43.201 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"overallMileageInKm":94,"overallTravelTimeInMin":142,"overallAverageMileageInKm":24,"overallAverageTravelTimeInMin":36,"overallAverageElectricConsumption":14.74,"overallAverageSpeedInKmph":40,"vehicleType":"ELECTRIC","detailedStatistics":[{"date":"2024-10-14"},{"date":"2024-10-15","tripIds":["2805151122"],"mileageInKm":45,"travelTimeInMin":65,"averageElectricConsumption":15.3,"averageRecuperation":3.2,"averageAuxConsumption":4.7,"averageSpeedInKmph":41},{"date":"2024-10-16","tripIds":["2805455441","2805327988"],"mileageInKm":49,"travelTimeInMin":77,"averageElectricConsumption":14.23,"averageRecuperation":3.15,"averageAuxConsumption":4.64,"averageSpeedInKmph":40},{"date":"2024-10-17"},{"date":"2024-10-18"},{"date":"2024-10-19"},{"date":"2024-10-20"}]}
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
data = deserialize(text)
^^^^^^^^^^^^^^^^^
File "<string>", line 7, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_fuel_consumption" of type float is missing in TripStatistics instance
2024-10-17 20:56:43.204 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
vehicle = await self.myskoda.get_vehicle(self.vin)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 264, in get_vehicle
vehicle.trip_statistics = await self.get_trip_statistics(vin)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 225, in get_trip_statistics
return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
result = self._deserialize(raw, TripStatistics.from_json)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
data = deserialize(text)

**Comment by WebSpider** [comment]
Thanks! What kind of car is this?

**Comment by equareo** [comment]
Škoda CitigoE iV

**Comment by WebSpider** [comment]
Thanks for the report. The issue is not solved yet, but will be "soon" :tm:
