### ISSUE TITLE
Some sensors cannot update since version 1.6.0

### ISSUE THREAD

**Issue by schneewe** [skodaconnect/homeassistant-myskoda#120]
**IMPORTANT NOTE**

You are using an integration that is still in development. We expect bugs, and hope to be able to fix them soon. Please expect bugs as well.
This integration currently only supports the MySkoda API compatible with the MySkoda App.

We have no intention to support features not in the MySkoda App, for instance the Skoda Essentials app.

**Please search issues in https://github.com/skodaconnect/myskoda and https://github.com/skodaconnect/homeassistant-myskoda for duplicates or fixes before reporting a new issue.**

**Describe the bug**
Some of the already working sensors, cannot get an update because of invalid states.
- Car position
- Current battery percentage
- main render url
- charger locked state

**Is this working in MySkoda app?***
Yes this is working, but only have ios app.

**Latest working release**
1.5.0

**Debug logs**

```
Error adding entity device_tracker.skoda_enyaq_position for domain device_tracker with platform myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/device_tracker.py", line 80, in extra_state_attributes
    if render := self.get_renders().get("main"):
                 ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/entity.py", line 60, in get_renders
    return {render.view_point: render.url for render in self.vehicle.info.renders}
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Info' object has no attribute 'renders'
---
Error adding entity None for domain binary_sensor with platform myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 823, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/myskoda/binary_sensor.py", line 114, in icon
    if self.is_on:
       ^^^^^^^^^^
  File "/config/custom_components/myskoda/binary_sensor.py", line 109, in is_on
    if ac.charger_lock_state != ChargerLockedState.INVALID:
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ChargerLockedState' has no attribute 'INVALID'
---
myskoda: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 571, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/sensor.py", line 350, in native_value
    return self.get_renders().get("main")
           ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/entity.py", line 60, in get_renders
    return {render.view_point: render.url for render in self.vehicle.info.renders}
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Info' object has no attribute 'renders'
---
Error adding entity sensor.skoda_enyaq_main_render_url for domain sensor with platform myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/sensor.py", line 350, in native_value
    return self.get_renders().get("main")
           ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/entity.py", line 60, in get_renders
    return {render.view_point: render.url for render in self.vehicle.info.renders}
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Info' object has no attribute 'renders'
```

**Installation:**
Docker

Edit @dvx76 : formatted logs

**Comment by dvx76** [comment]
@schneewe it looks like the myskoda package wasn't updated, only the homeassistant-myskoda.

E.g.

```
AttributeError: type object 'ChargerLockedState' has no attribute 'INVALID'
```

But this is present in `myskoda==0.8.4` (https://github.com/skodaconnect/myskoda/blob/v0.8.4/myskoda/models/common.py#L60), which is what should have been installed upon upgrading to version 1.6.0 of the integration.

I suspect if you scroll further back in your logs you will see an error when it tries to install `myskoda==0.8.4`.

This my fix itself by just restarting HA. If not, you can try deleting the device/integration and adding it again. Look for errors about installing the myskoda package.

**Comment by schneewe** [comment]
I removed the integration and also the pip dependency from homeassistant directory. If I restart and resinstall the integration, I can see that the module gets downloaded again.
If I search in the deps for the enum, I can find it. So I don't know what HA is using for a version. I will check that.

**Comment by schneewe** [comment]
Ok I don't know what happened in the container, but there was a little mess with the deps. 
But now I got it working. Thanks for pointing this out to the myskoda module.
