### ISSUE TITLE
MissingField: Field "profile_picture_url" of type str is missing in User instance

### ISSUE THREAD

**Issue by sonar98** [skodaconnect/homeassistant-myskoda#135]
````
Logger: myskoda.rest_api
Bron: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Eerst voorgekomen: 14:10:14 (3 gebeurtenissen)
Laatst gelogd: 15:10:35

Failed to deserialize data: {"id":"xxxxxxxxxxxxxxxx","email":"xxxxxxxxxx","firstName":"xxxxxxxxxx","lastName":"xxxxxxx","nickname":"xxxxxxxx","country":"NL","preferredLanguage":"nl","dateOfBirth":"xxxxxxxx","phone":"xxxxxxxx","billingAddress":{"country":"NL","city":"xxxxxxxx","street":"xxxxx","houseNumber":"xx","zipCode":"xxxxxxxx"},"capabilities":[{"id":"SPIN_MANAGEMENT"},{"id":"THIRD_PARTY_OFFERS"},{"id":"MARKETING_CONSENT"}],"preferredContactChannel":"MARKETING_BLOCKADES:EMAIL"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 36, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "profile_picture_url" of type str is missing in User instance

**Comment by WebSpider** [comment]
Thanks for this report! We'll fix this in the next version.
