### ISSUE TITLE
ValueError: 'UNKNOWN' is not a valid GarageErrorType

### ISSUE THREAD

**Issue by ChristianForstner** [skodaconnect/homeassistant-myskoda#139]
```
2024-10-26 12:19:52.714 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"vehicles":[],"errors":[{"type":"UNKNOWN","description":"Get user's garage failed."}]}
Traceback (most recent call last):
  File "<string>", line 11, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'UNKNOWN' is not a valid GarageErrorType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 13, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "type" of type GarageErrorType in GarageError has invalid value 'UNKNOWN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "errors" of type Optional[list[GarageError]] in Garage has invalid value [{'type': 'UNKNOWN', 'description': "Get user's garage failed."}]


2024-10-26 12:19:52.722 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MY@EMAIL.ADDRESS for myskoda
Traceback (most recent call last):
  File "<string>", line 11, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'UNKNOWN' is not a valid GarageErrorType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 13, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "type" of type GarageErrorType in GarageError has invalid value 'UNKNOWN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/__init__.py", line 46, in async_setup_entry
    vehicles = await myskoda.list_vehicle_vins()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 260, in list_vehicle_vins
    garage = (await self.rest_api.get_garage()).result
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 240, in get_garage
    result = self._deserialize(raw, Garage.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "errors" of type Optional[list[GarageError]] in Garage has invalid value [{'type': 'UNKNOWN', 'description': "Get user's garage failed."}]
```

Core: 2024.10.4
Supervisor: 2024.10.3
Operating System: 13.2
Frontend: 20241002.4
homeassistant-myskoda: 1.6.2

Car is a Skoda Enyaq (2024)

**Comment by WebSpider** [comment]
This has been fixed in 1.6.3
