### ISSUE TITLE
Error after initial install - failed Setup

### ISSUE THREAD

**Issue by minisweed** [skodaconnect/homeassistant-myskoda#145]
Good Evening all,

Let me start by saying my knowledge is very limited but does anyone have any idea how to resolve this?

![image](https://github.com/user-attachments/assets/2ca45567-7313-41c1-be37-da37f1929177)

Regards

**Comment by WebSpider** [comment]
Thanks for your report!

It seems like GB addresses are formatted a bit different. We'll adress this in an update.

**Comment by minisweed** [comment]
Cheers!

**Comment by scottgrobinson** [comment]
For reference - Full stack of the above

```
2024-10-29 18:49:10.620 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"positions":[{"type":"VEHICLE","gpsCoordinates":{"latitude":50.963509,"longitude":-1.532879},"address":{"city":"Romsey","country":"United Kingdom","countryCode":"GB"}}],"errors":[]}
Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "street" of type str is missing in Address instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 16, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "address" of type Address in Position has invalid value {'city': 'Romsey', 'country': 'United Kingdom', 'countryCode': 'GB'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "positions" of type list[Position] in Positions has invalid value [{'type': 'VEHICLE', 'gpsCoordinates': {'latitude': 50.963509, 'longitude': -1.532879}, 'address': {'city': 'Romsey', 'country': 'United Kingdom', 'countryCode': 'GB'}}]
2024-10-29 18:49:10.622 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "street" of type str is missing in Address instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 16, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "address" of type Address in Position has invalid value {'city': 'Romsey', 'country': 'United Kingdom', 'countryCode': 'GB'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 280, in get_vehicle
    vehicle.positions = await self.get_positions(vin)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 236, in get_positions
    return (await self.rest_api.get_positions(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 163, in get_positions
    result = self._deserialize(raw, Positions.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "positions" of type list[Position] in Positions has invalid value [{'type': 'VEHICLE', 'gpsCoordinates': {'latitude': 50.963509, 'longitude': -1.532879}, 'address': {'city': 'Romsey', 'country': 'United Kingdom', 'countryCode': 'GB'}}]
```

**Comment by WebSpider** [comment]
Awesome detail, just what we needed, thanks!
