### ISSUE TITLE
 Type float is missing in TripStatistics instance

### ISSUE THREAD

**Issue by SamA699** [skodaconnect/homeassistant-myskoda#160]
Hello, just tried the 1.6.5 with our citigo EV and got the Error: Einrichtung fehlgeschlagen, wird erneut versucht: Field "overall_average_fuel_consumption" of type float is missing in TripStatistics instance .... any suggestions?

**Comment by WebSpider** [comment]
Can you please copy/paste the entire error from your logs?

**Comment by SamA699** [comment]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.myskoda.coordinator
Quelle: helpers/update_coordinator.py:354
Integration: MySkoda (Dokumentation, Probleme)
Erstmals aufgetreten: 09:52:22 (22 Vorkommnisse)
Zuletzt protokolliert: 10:15:49

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 289, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 250, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_fuel_consumption" of type float is missing in TripStatistics instance
