### ISSUE TITLE
"overall_average_mileage_in_km" of type int is missing in TripStatistics instance

### ISSUE THREAD

**Issue by equareo** [skodaconnect/homeassistant-myskoda#169]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_mileage_in_km" of type int is missing in TripStatistics instance

got this error while trying to log in today, it worked ok one day ago. v1.7.0

car: Citigo

**Comment by WebSpider** [comment]
Thanks!

In order to properly fix this, can you please copy/paste full exception, not just the last bit?
Maybe more is missing than just `overall_average_mileage_in_km`, I'd like to fix it all at once.

**Comment by equareo** [comment]
Unexpected error fetching myskoda data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 289, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 250, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_mileage_in_km" of type int is missing in TripStatistics instance

This is all i get.

**Comment by WebSpider** [comment]
Thanks!
