### ISSUE TITLE
Field "heater_source" of type Optional[HeaterSource] in AirConditioning has invalid value 'ELECTRIC'

### ISSUE THREAD

**Issue by prvakt** [skodaconnect/homeassistant-myskoda#171]
Just noticed following exception when testing AC on my Superb iV

```
2024-11-04 10:08:25.346 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"state":"OFF","runningRequests":[],"targetTemperature":{"temperatureValue":21.5,"unitInCar":"CELSIUS"},"airConditioningWithoutExternalPower":true,"steeringWheelPosition":"LEFT","chargerConnectionState":"CONNECTED","chargerLockState":"LOCKED","windowHeatingState":{"front":"OFF","rear":"OFF","unspecified":"INVALID"},"heaterSource":"ELECTRIC","timers":[],"carCapturedTimestamp":"2024-11-04T09:06:03Z","errors":[{"type":"UNAVAILABLE_VEHICLE_INFORMATION","description":"APIs for obtaining seat heating status are not available"},{"type":"UNAVAILABLE_TIMERS_INFORMATION","description":"APIs for obtaining air conditioning timers are not available"}]}
Traceback (most recent call last):
File "<string>", line 76, in __mashumaro_from_json__
File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
return cls.__new__(cls, value)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
raise ve_exc
ValueError: 'ELECTRIC' is not a valid HeaterSource
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
data = deserialize(text)
^^^^^^^^^^^^^^^^^
File "<string>", line 78, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "heater_source" of type Optional[HeaterSource] in AirConditioning has invalid value 'ELECTRIC'
2024-11-04 10:08:25.347 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
File "<string>", line 76, in __mashumaro_from_json__
File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
return cls.__new__(cls, value)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
raise ve_exc
ValueError: 'ELECTRIC' is not a valid HeaterSource
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
vehicle = await self.myskoda.get_vehicle(self.vin)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 283, in get_vehicle
vehicle.air_conditioning = await self.get_air_conditioning(vin)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 238, in get_air_conditioning
return (await self.rest_api.get_air_conditioning(vin, anonymize=anonymize)).result
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 149, in get_air_conditioning
result = self._deserialize(raw, AirConditioning.from_json)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
data = deserialize(text)
^^^^^^^^^^^^^^^^^
File "<string>", line 78, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "heater_source" of type Optional[HeaterSource] in AirConditioning has invalid value 'ELECTRIC'
```

**Comment by prvakt** [comment]
just a note - I cant use this integration after this error. Just see setup failed and all sensors are unknown

**Comment by WebSpider** [comment]
Thanks, I will fix this today and release a new version
