### ISSUE TITLE
Can't log in. "Configuration error, will try again: Field "total_range_in_km" of type int is missing in DrivingRange instance"

### ISSUE THREAD

**Issue by BlaShDD** [skodaconnect/homeassistant-myskoda#187]
Car is an Octavia NX.

`2024-11-06 22:00:19.471 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v2/vehicle-stat - response: 200 (187 bytes) {"carType":"diesel","adBlueRange":19500,"primaryEngineRange":{"engineType":"diesel","currentSoCInPercent":54,"currentFuelLevelInPercent":54},"carCapturedTimestamp":"2024-11-06T20:18:28Z"}
2024-11-06 22:00:19.472 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"carType":"diesel","adBlueRange":19500,"primaryEngineRange":{"engineType":"diesel","currentSoCInPercent":54,"currentFuelLevelInPercent":54},"carCapturedTimestamp":"2024-11-06T20:18:28Z"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 22, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "total_range_in_km" of type int is missing in DrivingRange instance
2024-11-06 22:00:19.473 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 280, in get_vehicle
    vehicle.driving_range = await self.get_driving_range(vin)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 246, in get_driving_range
    return (await self.rest_api.get_driving_range(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 177, in get_driving_range
    result = self._deserialize(raw, DrivingRange.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 22, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "total_range_in_km" of type int is missing in DrivingRange instance
2024-11-06 22:00:19.473 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 6.386 seconds (success: False)
2024-11-06 22:00:21.565 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-06 22:00:21.582 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
`

**Comment by marz-xx** [comment]
I get the same error message for a Superb IV (plug-in hybrid). Let me know if you need my logs as well (then I'll try to find them.
Thanks for all the work you are doing on this!

**Comment by WebSpider** [comment]
No need for now, the change is pending a review and then it will be added to the next release
