### ISSUE TITLE
Error configuring the integration

### ISSUE THREAD

**Issue by edje** [skodaconnect/homeassistant-myskoda#196]
![image](https://github.com/user-attachments/assets/7faf3e26-0621-4ed7-94d4-eb27e23a4406)

See the logs from the logger. I have a Skoda Citigo E Iv. So far the integration is not working and not generating sensors etc.

`Logger: myskoda.rest_api
Bron: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Eerst voorgekomen: 10:17:43 (2 gebeurtenissen)
Laatst gelogd: 10:18:34

Failed to deserialize data: {"vehicleType":"ELECTRIC","detailedStatistics":[{"date":"2024-11-04"},{"date":"2024-11-05"},{"date":"2024-11-06"},{"date":"2024-11-07"},{"date":"2024-11-08"},{"date":"2024-11-09"},{"date":"2024-11-10"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_speed_in_kmph" of type int is missing in TripStatistics instance

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.myskoda.coordinator
Bron: helpers/update_coordinator.py:354
integratie: MySkoda (documentatie, problemen)
Eerst voorgekomen: 10:17:43 (4 gebeurtenissen)
Laatst gelogd: 10:19:25

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 289, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 250, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_speed_in_kmph" of type int is missing in TripStatistics instance`

**Comment by WebSpider** [comment]
Thanks!

It appears that **sometimes** the `overall_average_speed_in_kmph` is missing, where we expect it to be always present. This will be fixed in the next release.
