### ISSUE TITLE
MissingField: Field "overall_average_speed_in_kmph" of type int is missing in TripStatistics instance

### ISSUE THREAD

**Issue by twf75** [skodaconnect/homeassistant-myskoda#198]
**Describe the bug**
When starting the (newly added) integration, the setup fails with "MissingField: Field "overall_average_speed_in_kmph" of type int is missing in TripStatistics instance". And while it promises to retry, and does, that does not help a lot as it fails in the same way :)

**Is this working in MySkoda app?***
Hard to tell. In general, the MySkoda app works for me (Skoda Octavia Combi, petrol, 2020), and 'trip statistics' are visibile in the app. 

**Latest working release**
na. First install.

**Debug logs**
Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 85, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 289, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 250, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_speed_in_kmph" of type int is missing in TripStatistics instance

**Installation:**
 - Home Assistant, Hass OS, running in an unRaid virtual machine. 

**Additional context**
Never used the previous integration. MySkoda account age is about 5 months, if that's in any way relevant.

**Comment by dvx76** [comment]
Dup of #196 , fixed in https://github.com/skodaconnect/myskoda/pull/168, will come in next release.
