### ISSUE TITLE
Failed to setup in latest HA

### ISSUE THREAD

**Issue by PaulAntonDeen** [skodaconnect/homeassistant-myskoda#232]
**IMPORTANT NOTE**

You are using an integration that is still in development. We expect bugs, and hope to be able to fix them soon. Please expect bugs as well.
This integration currently only supports the MySkoda API compatible with the MySkoda App.

We have no intention to support features not in the MySkoda App, for instance the Skoda Essentials app.

**Please search issues in https://github.com/skodaconnect/myskoda and https://github.com/skodaconnect/homeassistant-myskoda for duplicates or fixes before reporting a new issue.**

**Describe the bug**
Integration will not load, deserialization failure.

**Is this working in MySkoda app?***
Logout and login in the MySkoda app, preferably on Android.
Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version.
App is working well.

**Latest working release**
If the problem started after updating to a new release, please state latest working release.
It was working in 2024.11.0 with MySkoda 1.8.0

**Debug logs**
If applicable, add debug logs. Debug logs help us locate and fix a problem quicker
```
2024-11-11 08:59:47.975 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"vehicleType":"HYBRID","detailedStatistics":[{"date":"2024-11-11"},{"date":"2024-11-12"},{"date":"2024-11-13"},{"date":"2024-11-14"},{"date":"2024-11-15"},{"date":"2024-11-16"},{"date":"2024-11-17"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance
2024-11-11 08:59:47.976 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 301, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance
2024-11-11 08:59:47.980 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 6.877 seconds (success: False)
2024-11-11 08:59:47.985 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:47.997 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:48.550 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:48.551 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:48.565 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:48.566 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:48.844 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:48.846 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:48.863 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:48.873 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:48.987 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:49.000 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:49.106 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:49.124 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:49.345 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:49.360 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:49.444 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:49.457 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:50.266 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:50.283 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:50.346 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:50.359 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:50.621 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:50.639 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:50.726 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:50.742 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:50.989 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:51.005 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:51.343 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:51.344 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:51.358 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:51.361 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:51.727 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:51.743 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:51.848 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:51.860 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:52.178 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:52.192 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:52.367 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:52.381 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:52.849 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:52.868 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:53.109 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:53.111 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-11-11 08:59:53.126 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-11-11 08:59:53.127 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
```

**Installation:**
 - Home Assistant variant: Hass OS 2024.11.1 with MySkoda 1.8.1

Python 3.12.3

Package    Version
---------- -------
awake      1.0
packaging  24.0
pathspec   0.12.1
pip        24.0
pulsemixer 1.5.1
pyparsing  3.1.2
PyYAML     6.0.2
setuptools 70.3.0
yamllint   1.35.1

**Additional context**
I tried restarts and reloads, confirmed app is working. Thanks for all your great work!
This is a Skoda Superb Plugin Hybrid from 2022.

**Comment by dvx76** [comment]
Duplicate of #219, fixed in skodaconnect/myskoda#176. Should be fixed in next release.
