### ISSUE TITLE
Cannot connect to MySkoda

### ISSUE THREAD

**Issue by marnixha** [skodaconnect/homeassistant-myskoda#25]
When setting up the integration in Homeassistant and after providing my MySkoda username and password I get the following erro in the integration window:

No devices or entities

Failed setup, will retry: 1 validation error for
Info capabilities -> capabilities -> 5 -> statuses -> 0 value is not a valid enumeration
member; permitted:
'DEACTIVATED_BY_ACTIVE_VEHICLE_USER','INSUFFUCIENT_BATTERY_LEVEL'
(type=type_error.enum;enum_values=....

and after a while:

No devices or entities
Failed setup, will retry: 1 validation error for Maintenance preferredServicePartner -> contact -> email field required (type=value_error.missing)

My car as an Enyaq 60.

In the logging I see:

This error originated from a custom integration.

Logger: custom_components.myskoda.coordinator
Source: helpers/update_coordinator.py:354
integration: MySkoda (documentation, issues)
First occurred: 4:41:47 PM (36 occurrences)
Last logged: 5:06:28 PM

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 181, in get_vehicle
    maintenance = await self.get_maintenance(vin)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 164, in get_maintenance
    return await self.rest_api.get_maintenance(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 121, in get_maintenance
    return Maintenance.parse_raw(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Maintenance
preferredServicePartner -> contact -> email
  field required (type=value_error.missing)

**Comment by dvx76** [comment]
`Info capabilities -> capabilities -> 5 -> statuses -> 0 value is not a valid enumeration` is likely fixed by skodaconnect/myskoda#11

`preferredServicePartner -> contact -> email field required (type=value_error.missing)` I'll fix here.

**Comment by dvx76** [comment]
Please wait for the next version to be released and retry.
