### ISSUE TITLE
Dezerialize error during initialize

### ISSUE THREAD

**Issue by reineo** [skodaconnect/homeassistant-myskoda#251]
I managed to install and configure the integration initially but now it only reports failure during initialization.

Car is Skoda Oactavia iV (Hybrid)

```
Logger: myskoda.rest_api
Källa: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:394
Inträffade först: 12:20:24 (115 händelser)
Senast loggade: 15:09:37

Failed to deserialize data: {"vehicleType":"HYBRID","detailedStatistics":[{"date":"2024-11-11"},{"date":"2024-11-12"},{"date":"2024-11-13"},{"date":"2024-11-14"},{"date":"2024-11-15"},{"date":"2024-11-16"},{"date":"2024-11-17"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance
```

```
Logger: custom_components.myskoda.coordinator
Källa: helpers/update_coordinator.py:382
integration: MySkoda ([dokumentation](https://github.com/skodaconnect/homeassistant-myskoda/blob/main/README.md), [ärenden](https://github.com/skodaconnect/homeassistant-myskoda/issues))
Inträffade först: 12:20:24 (115 händelser)
Senast loggade: 15:09:37

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 301, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance
```

**Comment by reineo** [comment]
MySkoda integration version is 1.8.1 and I'm running HA core 2024.11.1 on Hassio 13.2

**Comment by reineo** [comment]
Additional log record found at system restart

```
Logger: myskoda.rest_api
Källa: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:91
Inträffade först: 15:27:58 (3 händelser)
Senast loggade: 15:29:29

Invalid status for GET request to /v1/trip-statistics/[REDACTED-VIN]?offsetType=week&offset=0&timezone=Europe%2FBerlin: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 85, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/trip-statistics/[REDACTED-VIN]?offsetType=week&offset=0&timezone=Europe/Berlin'
```

**Comment by WebSpider** [comment]
This indicates a temporary error from the MySkoda side. We should improve our behaviour here so we don't fail the startup but retry

**Comment by reineo** [comment]
After multiple HA restarts and log level changes I can confirm that it started to behave a bit differently. No more parsing erros but all enitities are still listed as Unavailable though.. 

```
2024-11-11 16:12:28.673 DEBUG (MainThread) [myskoda.myskoda] IDK Authorization was successful.
2024-11-11 16:12:29.185 INFO (MainThread) [myskoda.mqtt] Connecting to MQTT with 58c130bb-ea25-412f-9ae7-e3f7d529e1a5/['REDACTED']
2024-11-11 16:12:29.373 INFO (MainThread) [myskoda.mqtt] Connected to MQTT
2024-11-11 16:12:30.890 DEBUG (MainThread) [myskoda.myskoda] Myskoda ready.
2024-11-11 16:12:31.054 DEBUG (MainThread) [custom_components.myskoda.coordinator] Performing scheduled update of all data for vin REDACTED
2024-11-11 16:12:34.520 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 3.467 seconds (success: True)
2024-11-11 16:12:34.544 DEBUG (MainThread) [custom_components.myskoda.coordinator] Performing scheduled update of all data for vin REDACTED
2024-11-11 16:12:41.070 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 6.525 seconds (success: True)
```

**Comment by ThraaxSession** [comment]
related: https://github.com/skodaconnect/myskoda/issues/192

**Comment by WebSpider** [comment]
Please try this with v1.8.2 of the integration

**Comment by reineo** [comment]
I'm just guessing here but it seems like one single Api request will corrupt all state when deserialize of unexpected response fails. This leads to other errors in code that expects valid state.

If an Api returns an unexpected response it should be gracefully handled. I.e create placeholder state (or not mutate state if already existing) to prevent other code sections not to break everything.

**Comment by reineo** [comment]
Installed 1.8.2 and everything looks good atm. If that it is because a bug being fixed or I got lucky with API requests not failing is to early to say :). Will update here if everything still works after a couple of hours.

**Comment by dvx76** [comment]
Thanks for the update. I'll close this so we can focus on open issues. Please create a new issue if you get deserialization errors again.

You're right in that API or deserialization errors for one endpoint shouldn't impact the whole integration. We should have an issue specifically for that somewhere. First initialization might be a special case because that's where entities get created so we really want parsed response for all endpoints there.

**Comment by reineo** [comment]
Sadly, less than 2 hours after updating to 1.8.2 everything stopped working again. 
Seems to be an error related to OAuth token refresh flow so probably unrelated.

```
Logger: homeassistant
Källa: /usr/src/homeassistant/homeassistant/runner.py:147
Inträffade först: 10:55:10 (1 händelser)
Senast loggade: 10:55:10

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 148, in _connect_and_listen
    password=await self.authorization.get_access_token(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 293, in get_access_token
    await self.refresh_token()
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 262, in refresh_token
    if await self._perform_refresh_token():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 241, in _perform_refresh_token
    async with self.session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 494, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```
