### ISSUE TITLE
Prerelease 1.3.0 won't start

### ISSUE THREAD

**Issue by sonar98** [skodaconnect/homeassistant-myskoda#27]
Version 1.3.0 gives an error when starting.

``````
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.myskoda.coordinator
Bron: helpers/update_coordinator.py:354
integratie: MySkoda (documentatie, problemen)
Eerst voorgekomen: 21:00:31 (14 gebeurtenissen)
Laatst gelogd: 21:14:53

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 65, in _async_update_data
    vehicles = await self.myskoda.get_all_vehicles()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 209, in get_all_vehicles
    return await gather(*(self.get_vehicle(vin) for vin in vins))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 199, in get_vehicle
    vehicle.charging = await self.get_charging(vin)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 140, in get_charging
    return await self.rest_api.get_charging(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 61, in get_charging
    return Charging.parse_raw(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Charging
status -> state
  field required (type=value_error.missing)

**Comment by dvx76** [comment]
Please enable debug and provide the line which looks like `"vin {vin}: received charging info: {response_text}"` which should be just before the error.

**Comment by sonar98** [comment]
````
2024-09-22 22:37:33.969 DEBUG (MainThread) [myskoda.rest_api] vin XXXXXXXXXXXXXXXXXX: received charging info: {"isVehicleInSavedLocation":false,"status":{"chargingRateInKilometersPerHour":0.0,"chargePowerInKw":0.0,"remainingTimeToFullyChargedInMinutes":0,"battery":{"remainingCruisingRangeInMeters":208000,"stateOfChargeInPercent":48}},"settings":{"targetStateOfChargeInPercent":80,"preferredChargeMode":"MANUAL","availableChargeModes":["MANUAL"],"chargingCareMode":"ACTIVATED","autoUnlockPlugWhenCharged":"OFF","maxChargeCurrentAc":"MAXIMUM","batterySupport":"DISABLED"},"carCapturedTimestamp":"2024-09-22T15:34:14Z","errors":[{"type":"STATUS_OF_CHARGING_NOT_AVAILABLE","description":"Status of charging is not available."}]}

**Comment by WebSpider** [comment]
I see not everything made it into the prerelease indeed. Thanks for letting us know!

**Comment by dvx76** [comment]
Closing, superseded by #28
