### ISSUE TITLE
Authentification fails: Cannot pair the car

### ISSUE THREAD

**Issue by domerich** [skodaconnect/homeassistant-myskoda#283]
This night the integration lost connection with my Enyaq. Deleting and setting up the integration fails.

```
`This error originated from a custom integration.

Logger: custom_components.myskoda.config_flow
Source: custom_components/myskoda/config_flow.py:97
integration: MySkoda (documentation, issues)
First occurred: 11:07:42 AM (2 occurrences)
Last logged: 11:09:39 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 77, in authorize
    self.idk_session = await self._get_idk_session()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 220, in _get_idk_session
    authentication = await self._enter_password(login_meta)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 164, in _enter_password
    async with self.session.get(location, allow_redirects=False) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 592, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /signin-service/v1/7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com/terms-and-conditions?relayState=e95820efa442b0c4261f5d1c61827ba5ab032fd3&canChangeCountryOfResidence=true&userId=42f4bf42-9810-493b-9059-d4ebb0e79787

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/myskoda/config_flow.py", line 97, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/myskoda/config_flow.py", line 57, in validate_input
    await hub.connect(data["email"], data["password"])
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 120, in connect
    await self.authorization.authorize(email, password)
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 79, in authorize
    raise AuthorizationFailedError from ex
myskoda.auth.authorization.AuthorizationFailedError`
```

**Comment by domerich** [comment]
Solution: Sign out in your mySkoda App on the iPhone, sign in again and accept the changed terms and conditions. Then it will work in Home Assistant

**Comment by gschot** [comment]
Try logging out of the MySkoda app and relogin. The reauth requests acceptance of a EULA. IF you accept that, it is done
