### ISSUE TITLE
Release 1.4 doesn't start if the SKODA profile is missing birth date and preferred contact channel

### ISSUE THREAD

**Issue by jrjuniortkf** [skodaconnect/homeassistant-myskoda#29]
After I added both to my SKODA profile using their app the integration loaded successfully. Do we really need this info in the SKODA profile?

Here are the logs:

Missing preferred contact channel:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 42, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "preferred_contact_channel" of type str is missing in User instance
2024-09-25 17:29:53.120 ERROR (MainThread) [custom_components.myskoda] Login with MySkoda failed.
Traceback (most recent call last):
  File "/config/custom_components/myskoda/__init__.py", line 40, in async_setup_entry
    await myskoda.connect(
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 70, in connect
    await self.mqtt.connect()
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 138, in connect
    while not await self._perform_connect():  # noqa: ASYNC110
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 104, in _perform_connect
    self.user = await self.api.get_user()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 102, in get_user
    return await self._make_get_request("/v1/users", User.from_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 42, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "preferred_contact_channel" of type str is missing in User instance
2024-09-25 17:29:53.864 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'count' when rendering '{{ value_json.count }}'`

Missing date of birth

`Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "date_of_birth" of type date is missing in User instance
2024-09-25 17:18:26.725 ERROR (MainThread) [custom_components.myskoda] Login with MySkoda failed.
Traceback (most recent call last):
  File "/config/custom_components/myskoda/__init__.py", line 40, in async_setup_entry
    await myskoda.connect(
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 70, in connect
    await self.mqtt.connect()
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 138, in connect
    while not await self._perform_connect():  # noqa: ASYNC110
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 104, in _perform_connect
    self.user = await self.api.get_user()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 102, in get_user
    return await self._make_get_request("/v1/users", User.from_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "date_of_birth" of type date is missing in User instance
2024-09-25 17:18:38.846 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'count' when rendering '{{ value_json.count }}'`

**Comment by MarcelMertens** [comment]
Same here, also missing phone number throws an error.
How did you set preferred contact channel?

**Comment by dvx76** [comment]
Fixing this.
