### ISSUE TITLE
Integration stopped requesting data after error from myskoda

### ISSUE THREAD

**Issue by prvakt** [skodaconnect/homeassistant-myskoda#298]
Got following response from myskoda when I started charging my Superb iV
```
2024-11-16 11:53:16.472 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/charging/TMB - response: 200 (638 bytes) {"isVehicleInSavedLocation":false,"status":{"battery":{}},"settings":{"availableChargeModes":[],"maxChargeCurrentAc":"MAXIMUM"},"carCapturedTimestamp":"2024-11-16T10:52:42Z","errors":[{"type":"CARE_MODE_IS_NOT_AVAILABLE","description":"Care mode is not available."},{"type":"AUTO_UNLOCK_IS_NOT_AVAILABLE","description":"Auto unlock is not available."},{"type":"CHARGE_LIMIT_IS_NOT_AVAILABLE","description":"Charge limit is not available."},{"type":"STATUS_OF_CHARGING_NOT_AVAILABLE","description":"Status of charging is not available."},{"type":"STATUS_OF_CONNECTION_NOT_AVAILABLE","description":"Status of connection is no available."}]}
```
Afterwards all sensors become uknown and it was necessary to restart complete integration because integration was not requesting any data from skoda except 
-  `https://mysmob.api.connect.skoda-auto.cz/api/v2/garage/vehicles/{vin}?connectivityGenerations=MOD1&connectivityGenerations=MOD2&connectivityGenerations=MOD3&connectivityGenerations=MOD4` 
- `https://mysmob.api.connect.skoda-auto.cz/api/v3/vehicle-maintenance/vehicles/{vin}` 
- `https://mysmob.api.connect.skoda-auto.cz/api/v1/users`

those errors are probably related to the response from above
```
Logger: myskoda.rest_api
Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:456
First occurred: 11:53:16 AM (1 occurrences)
Last logged: 11:53:16 AM

Failed to deserialize data: {"isVehicleInSavedLocation":false,"status":{"battery":{}},"settings":{"availableChargeModes":[],"maxChargeCurrentAc":"MAXIMUM"},"carCapturedTimestamp":"2024-11-16T10:52:42Z","errors":[{"type":"CARE_MODE_IS_NOT_AVAILABLE","description":"Care mode is not available."},{"type":"AUTO_UNLOCK_IS_NOT_AVAILABLE","description":"Auto unlock is not available."},{"type":"CHARGE_LIMIT_IS_NOT_AVAILABLE","description":"Charge limit is not available."},{"type":"STATUS_OF_CHARGING_NOT_AVAILABLE","description":"Status of charging is not available."},{"type":"STATUS_OF_CONNECTION_NOT_AVAILABLE","description":"Status of connection is no available."}]}
Traceback (most recent call last):
  File "<string>", line 9, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state_of_charge_in_percent" of type int is missing in Battery instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 34, in __mashumaro_from_json__
  File "<string>", line 11, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "battery" of type Battery in ChargingStatus has invalid value {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 454, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 36, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'battery': {}}
```
```
Logger: myskoda.rest_api
Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:456
First occurred: 11:53:16 AM (1 occurrences)
Last logged: 11:53:16 AM

Failed to deserialize data: {}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 454, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "car_captured_timestamp" of type datetime is missing in DrivingRange instance
```
```
Logger: custom_components.myskoda.coordinator
Source: helpers/debounce.py:137
integration: MySkoda ([documentation](https://github.com/skodaconnect/homeassistant-myskoda/blob/main/README.md), [issues](https://github.com/skodaconnect/homeassistant-myskoda/issues))
First occurred: 11:53:16 AM (1 occurrences)
Last logged: 11:53:16 AM

Unexpected exception from <bound method MySkodaDataUpdateCoordinator._update_driving_range of <custom_components.myskoda.coordinator.MySkodaDataUpdateCoordinator object at 0x7fbf48d41e50>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/config/custom_components/myskoda/coordinator.py", line 211, in _update_driving_range
    driving_range = await self.myskoda.get_driving_range(self.vin)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 280, in get_driving_range
    return (await self.rest_api.get_driving_range(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_driving_range
    result = self._deserialize(raw, DrivingRange.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 454, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "car_captured_timestamp" of type datetime is missing in DrivingRange instance
```
```
Logger: custom_components.myskoda.coordinator
Source: helpers/debounce.py:137
integration: MySkoda ([documentation](https://github.com/skodaconnect/homeassistant-myskoda/blob/main/README.md), [issues](https://github.com/skodaconnect/homeassistant-myskoda/issues))
First occurred: 11:53:16 AM (1 occurrences)
Last logged: 11:53:16 AM

Unexpected exception from <bound method MySkodaDataUpdateCoordinator._update_charging of <custom_components.myskoda.coordinator.MySkodaDataUpdateCoordinator object at 0x7fbf48d41e50>>
Traceback (most recent call last):
  File "<string>", line 9, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state_of_charge_in_percent" of type int is missing in Battery instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 34, in __mashumaro_from_json__
  File "<string>", line 11, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "battery" of type Battery in ChargingStatus has invalid value {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/config/custom_components/myskoda/coordinator.py", line 222, in _update_charging
    charging = await self.myskoda.get_charging(self.vin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 264, in get_charging
    return (await self.rest_api.get_charging(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 137, in get_charging
    result = self._deserialize(raw, Charging.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 454, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 36, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'battery': {}}
```

**Comment by prvakt** [comment]
*UPDATE* now I got 429, soI will let the MySkoda to cool down
```
24-11-16 12:05:51.973 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v2/vehicle-stat - response: 429 (157 bytes) Getting vehicle driving range status for vehicle VIN {TMBXXXXXXXXXXXXXX} cannot be performed due to maximum amount of requests
```

**Comment by WebSpider** [comment]
You found a corner case we have not seen yet, congrats! 😬

It seems the car has been out of touch with MySkoda for a while, and has lost its status there.

**Comment by RamsesczHA** [comment]
hi, 

i got same error. logs looks similiar.

Skoda Octavia 3 Combi Laurin & Klement 2018.

you are doing a great job, keep it up.

**Comment by RamsesczHA** [comment]
but after few system restarts looks good :-/
![image](https://github.com/user-attachments/assets/cdadb185-907a-4c12-affb-d6493ef379e5)

**Comment by danielrudolf** [comment]
I had the same problems. I had to log in online at myskoda and confirm the new terms and conditions.

**Comment by RadekHvizdos** [comment]
> I had the same problems. I had to log in online at myskoda and confirm the new terms and conditions.

Could you share the link you used for this? I can't seem to find it.

Thanks

**Comment by WebSpider** [comment]
> Got following response from myskoda when I started charging my Superb iV
> 
>SNIP
> 
> Afterwards all sensors become uknown and it was necessary to restart complete integration because integration was not requesting any data from skoda except
> 
> * `https://mysmob.api.connect.skoda-auto.cz/api/v2/garage/vehicles/{vin}?connectivityGenerations=MOD1&connectivityGenerations=MOD2&connectivityGenerations=MOD3&connectivityGenerations=MOD4`
> * `https://mysmob.api.connect.skoda-auto.cz/api/v3/vehicle-maintenance/vehicles/{vin}`
> * `https://mysmob.api.connect.skoda-auto.cz/api/v1/users`
> 
> those errors are probably related to the response from above

I took a look at this error state, and it must be because the MySkoda API was in an error state. 

We _ALWAYS_ request those 3 URL's in a full update, but the library depends on retrieving capabilities to know if more is supported by your car. Apparently, the MySkoda API was returning that your car did not have the correct capabilities, or they were in an error state.

If this happens next time, it would be interesting to see if the integration can auto-recover from this. Looking at the code, I don't see why it cannot.

**Comment by prvakt** [comment]
yeah it looks like if I overload the API with too many requests (especially too many logins because of testing new features and often restarts), MySkoda API return empty list of capabilities which resulted in integration stopped requesting new data... But after cooldown (next day), seems like everything is correct again so I'm closing this issue

**Comment by prvakt** [comment]
just a note: it happened to me again as I was testing auxiliary heater too much, and can confirm integration was able to self recover after API returned back to normal.. So we are fine here... 

Interestingly MySkoda API was still working but only following capabilities were returned (it went back to normal at 01:00 AM )
```
 "capabilities": [
                {
                    "id": "LOYALTY_PROGRAM",
                    "statuses": []
                },
                {
                    "id": "SUBSCRIPTIONS",
                    "statuses": []
                },
                {
                    "id": "CAR_FEEDBACK",
                    "statuses": []
                },
                {
                    "id": "LOYALTY_PROGRAM_WORLDWIDE",
                    "statuses": []
                },
                {
                    "id": "OUTSIDE_TEMPERATURE",
                    "statuses": []
                },
                {
                    "id": "SERVICE_PARTNER",
                    "statuses": []
                },
                {
                    "id": "MISUSE_PROTECTION",
                    "statuses": []
                }
            ]
```
and most of the endpoints were returning error 500...

there were few parsing errors as some fields were returned with UNKNOWN state, but I will fix those in myskoda lib later
