### ISSUE TITLE
Unable to install. Unexpected error…

### ISSUE THREAD

**Issue by slundmark** [skodaconnect/homeassistant-myskoda#328]
When the config wizard starts and I put in my MySkoda credentials I get the following error:

This error originated from a custom integration.

Logger: custom_components.myskoda.config_flow
Source: custom_components/myskoda/config_flow.py:103
integration: MySkoda (documentation, issues)
First occurred: 18:11:01 (1 occurrences)
Last logged: 18:11:01

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/myskoda/config_flow.py", line 103, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/myskoda/config_flow.py", line 62, in validate_input
    await hub.connect(data["email"], data["password"])
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 120, in connect
    await self.authorization.authorize(email, password)
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 77, in authorize
    self.idk_session = await self._get_idk_session()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 222, in _get_idk_session
    authentication = await self._enter_password(login_meta)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 165, in _enter_password
    raise TermsAndConditionsError(location)
myskoda.auth.authorization.TermsAndConditionsError: /signin-service/v1/7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com/terms-and-conditions?relayState=40f5371e3872cecb2ab6e2519e127a3d3e658dcf&canChangeCountryOfResidence=true&userId=5d3a9cc9-10c0-4def-a694-33fc5c6e6901

I installed using HACS (if that’s any help).

**Comment by dvx76** [comment]
Please search issues first, there are now dozens of reported cases for the same thing: https://github.com/skodaconnect/homeassistant-myskoda/issues?q=%22terms-and-conditions%22

There are new terms and conditions to accept. You get prompted on login. To force this log out and then back in with the MySkoda mobile app and you will be prompted to accept the new T&C. After that the integration should work again.
