### ISSUE TITLE
Detected blocking call warning from Generate Fixtures button

### ISSUE THREAD

**Issue by prvakt** [skodaconnect/homeassistant-myskoda#353]
There is a warning generated when Generate Fixtures button is pressed in `v1.11.0`

```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: November 26, 2024 at 5:40:35 PM (3 occurrences)
Last logged: November 26, 2024 at 5:40:35 PM

Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'myskoda' at custom_components/myskoda/button.py, line 129: result = await self.coordinator.myskoda.generate_get_fixture( (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 680: return os.listdir(self.root or '.')), please create a bug report at https://github.com/skodaconnect/homeassistant-myskoda/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action await self.async_press() File "/config/custom_components/myskoda/button.py", line 129, in async_press result = await self.coordinator.myskoda.generate_get_fixture(
Detected blocking call to read_text with args (PosixPath('/usr/local/lib/python3.12/site-packages/myskoda-0.13.0.dist-info/METADATA'),) inside the event loop by custom integration 'myskoda' at custom_components/myskoda/button.py, line 129: result = await self.coordinator.myskoda.generate_get_fixture( (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 819: return self._path.joinpath(filename).read_text(encoding='utf-8')), please create a bug report at https://github.com/skodaconnect/homeassistant-myskoda/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#read_text Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action await self.async_press() File "/config/custom_components/myskoda/button.py", line 129, in async_press result = await self.coordinator.myskoda.generate_get_fixture(
Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.12/site-packages/myskoda-0.13.0.dist-info/METADATA'),) inside the event loop by custom integration 'myskoda' at custom_components/myskoda/button.py, line 129: result = await self.coordinator.myskoda.generate_get_fixture( (offender: /usr/local/lib/python3.12/pathlib.py, line 1027: with self.open(mode='r', encoding=encoding, errors=errors) as f:), please create a bug report at https://github.com/skodaconnect/homeassistant-myskoda/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action await self.async_press() File "/config/custom_components/myskoda/button.py", line 129, in async_press result = await self.coordinator.myskoda.generate_get_fixture(
```

**Comment by WebSpider** [comment]
Cause here is https://github.com/skodaconnect/myskoda/pull/246 that imports something that has blocking calls.
