### ISSUE TITLE
Error on initialization:  Field "status" of type Optional[ChargingStatus] in Charging has invalid value 

### ISSUE THREAD

**Issue by robertkonstanzer** [skodaconnect/homeassistant-myskoda#364]
**Describe the bug**
After upgrading from 1.10.0 to 1.11.1 there are errors when initializing the plugin. I tried with 1.11.0, 1.11.1 and 1.12.0 all with the same problem. I then tried 1.10.0 again (which was working), but unfortunately it doesn't start as well. 

Error on UI
` Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'chargePowerInKw': 0.0, 'state': 'CONNECT_CABLE', 'battery': {'remainingCruisingRangeInMeters': 39000}}`

Car: Skoda Kodiaq 2024 Hybrid 

**Latest working release**
Problem occurs in all versions. Latest working version was 1.10.0, but downgrade to that doesn't solve the problem. 

**Debug logs**
2024-11-28 14:03:37.615 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"isVehicleInSavedLocation":false,"status":{"chargePowerInKw":0.0,"state":"CONNECT_CABLE","battery":{"remainingCruisingRangeInMeters":39000}},"settings":{"targetStateOfChargeInPercent":80,"preferredChargeMode":"MANUAL","availableChargeModes":["MANUAL"],"autoUnlockPlugWhenCharged":"OFF","maxChargeCurrentAc":"MAXIMUM"},"carCapturedTimestamp":"2024-11-27T17:02:51Z","errors":[{"type":"CARE_MODE_IS_NOT_AVAILABLE","description":"Care mode is not available."}]}
Traceback (most recent call last):
  File "<string>", line 9, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state_of_charge_in_percent" of type int is missing in Battery instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 38, in __mashumaro_from_json__
  File "<string>", line 11, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "battery" of type Battery in ChargingStatus has invalid value {'remainingCruisingRangeInMeters': 39000}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 519, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 40, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'chargePowerInKw': 0.0, 'state': 'CONNECT_CABLE', 'battery': {'remainingCruisingRangeInMeters': 39000}}
2024-11-28 14:03:37.617 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 9, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state_of_charge_in_percent" of type int is missing in Battery instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 38, in __mashumaro_from_json__
  File "<string>", line 11, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "battery" of type Battery in ChargingStatus has invalid value {'remainingCruisingRangeInMeters': 39000}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 108, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 364, in get_vehicle
    vehicle.charging = await self.get_charging(vin)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 298, in get_charging
    return (await self.rest_api.get_charging(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 145, in get_charging
    result = self._deserialize(raw, Charging.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 519, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 40, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'chargePowerInKw': 0.0, 'state': 'CONNECT_CABLE', 'battery': {'remainingCruisingRangeInMeters': 39000}}
2024-11-28 14:03:37.619 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 7.837 seconds (success: False)
2024-11-28 14:03:40.007 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ

**Installation:**
 - Home Assistant OS - everything is up to date

**Comment by robertkonstanzer** [comment]
Could be similar to https://github.com/skodaconnect/homeassistant-myskoda/issues/298

**Comment by WebSpider** [comment]
Thanks for your report!

The actual problem lies here:
`mashumaro.exceptions.MissingField: Field "state_of_charge_in_percent" of type int is missing in Battery instance`

Your car does not report a battery state of charge, where we expect it to always be there. We'll fix this.
