### ISSUE TITLE
[Bug] REST API returning unknown state

### ISSUE THREAD

**Issue by LasseHedeby** [skodaconnect/homeassistant-myskoda#38]
This morning after my Enyaq has charged and begun to heat the car, I got this error in the log

```
Logger: myskoda.rest_api
Kilde: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:43
Første forekomst: 05.08.23 (1 forekomster)
Senest logget: 05.08.23

Failed to load data from url /v2/air-conditioning/TMBJC9NY5MF021749. Return value was '{"estimatedDateTimeToReachTargetTemperature":"2024-09-27T03:15:23.655641679Z","state":"HEATING","runningRequests":[],"targetTemperature":{"temperatureValue":22.0,"unitInCar":"CELSIUS"},"airConditioningAtUnlock":true,"windowHeatingEnabled":true,"steeringWheelPosition":"LEFT","seatHeatingActivated":{"frontLeft":false,"frontRight":false},"chargerConnectionState":"CONNECTED","chargerLockState":"LOCKED","windowHeatingState":{"front":"OFF","rear":"OFF","unspecified":"INVALID"},"timers":[{"id":1,"enabled":true,"time":"05:15","type":"RECURRING","selectedDays":["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY"]},{"id":2,"enabled":false,"time":"00:00","type":"ONE_OFF","selectedDays":["SATURDAY"]}],"carCapturedTimestamp":"2024-09-27T03:08:00Z","errors":[]}'
Traceback (most recent call last):
  File "<string>", line 62, in __mashumaro_from_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'HEATING' is not a valid OnOffState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 64, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "state" of type OnOffState in AirConditioning has invalid value 'HEATING'
```

**Comment by WebSpider** [comment]
Thankyou for this message. 

It contains new information about the car that we have not seen yet, and will incorporate into the library. Once that is done, this issue will be closed.
