### ISSUE TITLE
NS73N5-2022  not giving any entities

### ISSUE THREAD

**Issue by pieterdevriesch** [skodaconnect/homeassistant-myskoda#380]
**Describe the bug**

After installing the integration and restarting, I logged in with my SkodaID and the integration is loaded. However it only shows 2 entities: generat

**Is this working in MySkoda app?***
MySkoda app is working normally.

**Debug logs**
`Logger: myskoda.rest_api
Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:100
First occurred: 15:53:50 (7 occurrences)
Last logged: 15:54:00

Invalid status for GET request to /v2/air-conditioning/TMBJB9NS0N8018391/auxiliary-heating: 429
Invalid status for GET request to /v1/vehicle-health-report/warning-lights/TMBJB9NS0N8018391: 500
Invalid status for GET request to /v1/charging/TMBJB9NS0N8018391: 429
Invalid status for GET request to /v2/vehicle-status/TMBJB9NS0N8018391/driving-range: 429
Invalid status for GET request to /v1/trip-statistics/TMBJB9NS0N8018391?offsetType=week&offset=0&timezone=Europe%2FBerlin: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 94, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v2/vehicle-status/TMBJB9NS0N8018391'`

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised]
 - Python version (when running Core or Supervised) [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

**Additional context**

**Comment by pieterdevriesch** [comment]
accidental duplicate
