### ISSUE TITLE
 no request for confirmation of the terms of use 

### ISSUE THREAD

**Issue by Excellsior1985** [skodaconnect/homeassistant-myskoda#418]
i have a problem that there is no request to confirm the terms of use. this causes the login to fail. the error is according to the log:

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.myskoda.config_flow
Quelle: custom_components/myskoda/config_flow.py:108
Integration: MySkoda (Dokumentation, Probleme)
Erstmals aufgetreten: 12:52:07 (1 Vorkommnisse)
Zuletzt protokolliert: 12:52:07

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/myskoda/config_flow.py", line 108, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/myskoda/config_flow.py", line 65, in validate_input
    await hub.connect(data["email"], data["password"])
  File "/usr/local/lib/python3.13/site-packages/myskoda/myskoda.py", line 128, in connect
    await self.authorization.authorize(email, password)
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 77, in authorize
    self.idk_session = await self._get_idk_session()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 222, in _get_idk_session
    authentication = await self._enter_password(login_meta)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 165, in _enter_password
    raise TermsAndConditionsError(location)
myskoda.auth.authorization.TermsAndConditionsError: /signin-service/v1/7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com/terms-and-conditions?relayState=f54f734f19ffca0c1f9480eb93e482f141850a82&canChangeCountryOfResidence=true&userId=

**Comment by prvakt** [comment]
you need to do this from MySkoda app on your phone. Please log-off and log-in again

**Comment by Excellsior1985** [comment]
such a simple solution! many thanks for the quick help!

**Comment by Excellsior1985** [comment]
such a simple solution! many thanks for the quick help!
