### ISSUE TITLE
Failed to initialize 

### ISSUE THREAD

**Issue by MikeyMan83** [skodaconnect/homeassistant-myskoda#449]
during setup I'm getting the message that it had failed to initialize.

![Screenshot_20241215-123346](https://github.com/user-attachments/assets/6c4ec574-a3af-4c4a-8d56-75238f1a5b96)

I do see my vins and licence plates, so something is working.

Latest home assistant version running.

**Comment by prvakt** [comment]
please provide full exception otherwise we don't know what failed to deserialize..

**Comment by MikeyMan83** [comment]
```
Logger: myskoda.rest_api
Bron: /usr/local/lib/python3.13/site-packages/myskoda/rest_api.py:521
Eerst voorgekomen: 12:09:00 (5 gebeurtenissen)
Laatst gelogd: 12:33:07

Failed to deserialize data: {"vehicles":[{"vin":"TMBJW9PS9ST029416","name":"Kodiaq","licensePlate":"GTH59J","state":"ACTIVATED","devicePlatform":"MBB_ODP","systemModelId":"PS7DYC","title":"Škoda Kodiaq","renders":[],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/baseps7v25100002/8X8Xpe9znyGTtA7UhkaDYRCM3lW-4ovWKM6OSzHrRYc_Csk2E-U7Ks.DEn5MWiQB1Hxlu3oq-A-19201080dayvext_side1080.png?v=638691074570000000","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0},{"vin":"TMBEP6NHXJ4509249","name":"Skoda Rapid","licensePlate":"PS164D","state":"RESET_SPIN","devicePlatform":"MBB","systemModelId":"NH13M4","title":"Škoda Rapid Spaceback","renders":[],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/transnh1b20180219/F6F6Q--59naqmg3ejy-sRYfJliLpHCnbFWP-pZ0Kwlf35c2uYy.-0NPKfeJXpt7aUv13hrx-0tvazTnfgrPiXEMkR-19201080dayvext_side1080.png?v=638676466315113906","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":1}]}
Traceback (most recent call last):
  File "<string>", line 22, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.13/enum.py", line 722, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 1189, in __new__
    raise ve_exc
ValueError: 'RESET_SPIN' is not a valid VehicleState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 10, in __mashumaro_from_json__
  File "<string>", line 24, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "state" of type VehicleState in GarageEntry has invalid value 'RESET_SPIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/rest_api.py", line 519, in _deserialize
    data = deserialize(text)
  File "<string>", line 12, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "vehicles" of type Optional[list[GarageEntry]] in Garage has invalid value [{'vin': 'xxx', 'name': 'Kodiaq', 'licensePlate': 'xxx', 'state': 'ACTIVATED', 'devicePlatform': 'MBB_ODP', 'systemModelId': 'PS7DYC', 'title': 'Škoda Kodiaq', 'renders': [], 'compositeRenders': [{'layers': [{'url': 'https://iprenders.blob.core.windows.net/baseps7v25100002/8X8Xpe9znyGTtA7UhkaDYRCM3lW-4ovWKM6OSzHrRYc_Csk2E-U7Ks.DEn5MWiQB1Hxlu3oq-A-19201080dayvext_side1080.png?v=638691074570000000', 'viewPoint': 'exterior_side', 'type': 'REAL', 'order': 0}], 'viewType': 'UNMODIFIED_EXTERIOR_SIDE'}], 'priority': 0}, {'vin': 'xxx', 'name': 'Skoda Rapid', 'licensePlate': 'xxx', 'state': 'RESET_SPIN', 'devicePlatform': 'MBB', 'systemModelId': 'NH13M4', 'title': 'Škoda Rapid Spaceback', 'renders': [], 'compositeRenders': [{'layers': [{'url': 'https://iprenders.blob.core.windows.net/transnh1b20180219/F6F6Q--59naqmg3ejy-sRYfJliLpHCnbFWP-pZ0Kwlf35c2uYy.-0NPKfeJXpt7aUv13hrx-0tvazTnfgrPiXEMkR-19201080dayvext_side1080.png?v=638676466315113906', 'viewPoint': 'exterior_side', 'type': 'REAL', 'order': 0}], 'viewType': 'UNMODIFIED_EXTERIOR_SIDE'}], 'priority': 1}]
```

**Comment by prvakt** [comment]
thanks, we will add `RESET_SPIN` into state enumeration.

If you want to overcome this issue, you need to reset SPIN on Skoda Rapid vehicle

**Comment by MikeyMan83** [comment]
Will do, thanks!

**Comment by MikeyMan83** [comment]
Seems spin cannot be reset without connect subscription.

**Comment by prvakt** [comment]
> Seems spin cannot be reset without connect subscription.

In that case, I would like to ask you to wait for new version. I have made necessary changes in our lib so next release will have this problem fixed and initialization of integration should be successful

**Comment by WebSpider** [comment]
Please try again with 1.16.1
