### ISSUE TITLE
Field "city" of type str is missing in Address instance

### ISSUE THREAD

**Issue by fulcrum1929** [skodaconnect/homeassistant-myskoda#47]
During the integration initialization the following error occurs:

---------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "positions" of type list[Position] in Positions has invalid value [{'type': 'VEHICLE', 'gpsCoordinates': {'latitude': XXXXX, 'longitude': XXXXX}, 'address': {'country': 'Italy', 'countryCode': 'IT', 'street': "XXXXX", 'houseNumber': 'XXXXX', 'zipCode': 'XXXXX'}}]
2024-09-29 11:51:26.484 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "<string>", line 7, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "city" of type str is missing in Address instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 16, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "address" of type Address in Position has invalid value {'country': 'Italy', 'countryCode': 'IT', 'street': "XXXXX", 'houseNumber': 'XXXXX', 'zipCode': 'XXXXX'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 216, in get_vehicle
    vehicle.positions = await self.get_positions(vin)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 175, in get_positions
    return await self.rest_api.get_positions(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 73, in get_positions
    return await self._make_get_request(f"/v1/maps/positions?vin={vin}", Positions.from_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "positions" of type list[Position] in Positions has invalid value [{'type': 'VEHICLE', 'gpsCoordinates': {'latitude': XXXXX, 'longitude': XXXXX}, 'address': {'country': 'Italy', 'countryCode': 'IT', 'street': "XXXXX", 'houseNumber': 'XXXXX', 'zipCode': 'XXXXX'}}]
2024-09-29 11:51:26.500 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 3.629 seconds (success: False)

**Comment by WebSpider** [comment]
Thank you for this report. Apparently, Skoda does not make a City a mandatory part of an address. We will address the issue and let you know in which version it will be solved.

**Comment by WebSpider** [comment]
This has been fixed and will be released in the next version.

**Comment by WebSpider** [comment]
This has been released with v1.4.3, please provide your feedback if there is any issue remaining, thanks!
