### ISSUE TITLE
Failed setup, will retry: Incomplete update received

### ISSUE THREAD

**Issue by zipposi** [skodaconnect/homeassistant-myskoda#489]
**Describe the bug**
After the last update the integration no longer connect to the Škoda services. The app works as usual.. I tried do uninstall and reinstall the integration, the result is the same.

![image](https://github.com/user-attachments/assets/42181bd8-775b-4298-b4c9-6c96ba476aa0)

**Is this working in MySkoda app?***
I loged out and reloged in the MySkoda app, no problems or warnings.

**Latest working release**
It stopped working after the last update (I noticed it around 20.12.2024). But not sure, because it took me a few days to see the problem.

**Debug logs**
```
Logger: myskoda.rest_api
Source: /usr/local/lib/python3.13/site-packages/myskoda/rest_api.py:103
First occurred: 18:38:10 (5 occurrences)
Last logged: 18:39:12

Invalid status for GET request to /v1/vehicle-automatization/TMBZZZAAZMD802498/departure/timers: 500
Invalid status for GET request to /v1/vehicle-automatization/TMBZZZAAZMD802498/departure/timers: 429
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/rest_api.py", line 97, in _make_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-automatization/TMBZZZAAZMD802498/departure/timers'
```

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, on Home Assistant Green HW.
 - Python version - don't know - probably up-to-date, because everything is updated.

**Additional context**
After reinstalling there are no errors after entering username and password, but after this is finished there are no devices and the error is displayed in the integration module.

**Comment by dvx76** [comment]
The only thing the log extract shows are the Skoda API returning HTTP 500 (internal server error) and 429 (rate limiting). If you believe this is caused by the latest version you can force HACS to install an older version to test that theory. But by the looks of it the problem is due to errors/limit coming from the API.

**Comment by zipposi** [comment]
What can I do about it? If is the API limit, why is thew app working - isn't the same access (same user/pass..)?

**Comment by zipposi** [comment]
BTW: Thanks for the integration. Now I have a problem, but I really appreciate your work.

**Comment by zipposi** [comment]
Is enough to wait a few days and then re-enable the integration?

**Comment by prvakt** [comment]
please try again tomorrow.. usually MySkoda resets those API limits after midnight.. We have added departure endpoint recently for cars with departure timers capability and probably this is causing problem for your car.. I will have a look on this, but can take some time because of Christmas 🎅 May I know what car you have?

**Comment by Dedier** [comment]
> update: if is it CitigoE iV, it looks like this car is very sensitive and with very low API limit for some endpoints

I've the same issue, my car is a CitigoE iV. I've waited almost a whole day to make sure the rate limit was removed (disabled the app to make sure it didn't connect the Skoda). I just enabled it again and this is the first part of the log file. I might have overlooked something important, but there is quite some sensitive information in the logfile, therefor didn't want to upload the whole file. Please let me know if I can do some other testing / missed something important in the logfile I can add to assist with finding the solution. I'm running version 1.17.2 and tried to newly install the integration (didn't test previous versions). 

`2024-12-24 00:45:57.105 WARNING (MainThread) [myskoda.auth.authorization] Retrying failed request to refresh token (0/5). Retrying...
2024-12-24 00:45:58.206 WARNING (MainThread) [myskoda.auth.authorization] Retrying failed request to refresh token (1/5). Retrying...
2024-12-24 00:45:59.315 WARNING (MainThread) [myskoda.auth.authorization] Retrying failed request to refresh token (2/5). Retrying...
2024-12-24 00:46:55.688 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v2/air-conditioning/***/auxiliary-heating: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 97, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v2/air-conditioning/***/auxiliary-heating'
2024-12-24 00:46:57.706 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/vehicle-automatization/***/departure/timers: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 97, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-automatization/***/departure/timers'
2024-12-24 00:47:02.995 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-12-24 00:47:03.007 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
2024-12-24 00:47:03.010 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-12-24 00:47:03.015 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ`

The pinging goes on for a bit. Then this is send 124 times in approx 100ms:
`2024-12-24 00:47:26.409 DEBUG (MainThread) [myskoda.mqtt] Received PUBLISH (d0, q0, r0, m0), '***/***/operation-request/vehicle-wakeup/wakeup', ...  (153 bytes)`

The response is about 250 times this:
`2024-12-24 00:47:26.540 DEBUG (MainThread) [myskoda.mqtt] An operation 'wakeup' is now in progress. Trace id: ***
2024-12-24 00:47:26.540 DEBUG (MainThread) [myskoda.mqtt] Message (operation-request) received for *** on topic vehicle-wakeup/wakeup: b'{"version":1,"operation":"wakeup","status":"IN_PROGRESS","traceId":"***","requestId":"***"}'`

With sometimes this in between:
`2024-12-24 00:47:26.560 DEBUG (MainThread) [custom_components.myskoda.coordinator] Manually updated myskoda data`

Eventually it comes to:
`2024-12-24 00:47:26.663 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP
2024-12-24 00:47:26.676 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-auto - response: 500 (54 bytes) Unknown error occurred during getting departure timers
2024-12-24 00:47:26.676 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/vehicle-automatization/***/departure/timers: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 97, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-automatization/***/departure/timers'
2024-12-24 00:47:26.678 DEBUG (MainThread) [custom_components.myskoda.error_handlers] Received error 500 with content Internal Server Error
2024-12-24 00:47:26.679 WARNING (MainThread) [custom_components.myskoda.error_handlers] Error requesting vehicle from MySkoda API: Internal Server Error (500), ignoring this
2024-12-24 00:47:26.679 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 2.671 seconds (success: False)`

**Comment by flofricke** [comment]
Hi, 

I also have a Citigo eIV and I have the same problem. The Citigo's hardware is older and an SMS is probably sent to the vehicle to wake it up and query the current data. Hence the rate limit, I assume. 

It would be great if the end points could be configured, especially for this vehicle. Everything worked great with one of the last versions. I use the information at 15-minute intervals to stop charging at 80%.

**Comment by prvakt** [comment]
> > update: if is it CitigoE iV, it looks like this car is very sensitive and with very low API limit for some endpoints
> 
> I've the same issue, my car is a CitigoE iV. I've waited almost a whole day to make sure the rate limit was removed (disabled the app to make sure it didn't connect the Skoda). I just enabled it again and this is the first part of the log file. I might have overlooked something important, but there is quite some sensitive information in the logfile, therefor didn't want to upload the whole file. Please let me know if I can do some other testing / missed something important in the logfile I can add to assist with finding the solution. I'm running version 1.17.2 and tried to newly install the integration (didn't test previous versions).
> 
> 
```2024-12-24 00:45:57.105 WARNING (MainThread) [myskoda.auth.authorization] Retrying failed request to refresh token (0/5). Retrying... 
2024-12-24 00:45:58.206 WARNING (MainThread) [myskoda.auth.authorization] Retrying failed request to refresh token (1/5). Retrying... 
2024-12-24 00:45:59.315 WARNING (MainThread) [myskoda.auth.authorization] Retrying failed request to refresh token (2/5). Retrying... 
2024-12-24 00:46:55.688 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v2/air-conditioning/***/auxiliary-heating: 500 Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 97, in _make_request response.raise_for_status() File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v2/air-conditioning/***/auxiliary-heating' 
2024-12-24 00:46:57.706 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/vehicle-automatization/***/departure/timers: 500 Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 97, in _make_request response.raise_for_status() File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-automatization/***/departure/timers' 
2024-12-24 00:47:02.995 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ 
2024-12-24 00:47:03.007 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ 
2024-12-24 00:47:03.010 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP 
2024-12-24 00:47:03.015 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ
```
> 
> The pinging goes on for a bit. Then this is send 124 times in approx 100ms: 
```
2024-12-24 00:47:26.409 DEBUG (MainThread) [myskoda.mqtt] Received PUBLISH (d0, q0, r0, m0), '***/***/operation-request/vehicle-wakeup/wakeup', ... (153 bytes)
```
> 
> The response is about 250 times this: 
```
2024-12-24 00:47:26.540 DEBUG (MainThread) [myskoda.mqtt] An operation 'wakeup' is now in progress. Trace id: *** 
2024-12-24 00:47:26.540 DEBUG (MainThread) [myskoda.mqtt] Message (operation-request) received for *** on topic vehicle-wakeup/wakeup: b'{"version":1,"operation":"wakeup","status":"IN_PROGRESS","traceId":"***","requestId":"***"}'
```
> 
> With sometimes this in between: 
```
2024-12-24 00:47:26.560 DEBUG (MainThread) [custom_components.myskoda.coordinator] Manually updated myskoda data
```
> 
> Eventually it comes to: 
```
2024-12-24 00:47:26.663 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP 
2024-12-24 00:47:26.676 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-auto - response: 500 (54 bytes) Unknown error occurred during getting departure timers 
2024-12-24 00:47:26.676 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/vehicle-automatization/***/departure/timers: 500 Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 97, in _make_request response.raise_for_status() File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-automatization/***/departure/timers' 
2024-12-24 00:47:26.678 DEBUG (MainThread) [custom_components.myskoda.error_handlers] Received error 500 with content Internal Server Error 
2024-12-24 00:47:26.679 WARNING (MainThread) [custom_components.myskoda.error_handlers] Error requesting vehicle from MySkoda API: Internal Server Error (500), ignoring this 
2024-12-24 00:47:26.679 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 2.671 seconds (success: False)
```

This is very strange and it really seems MySkoda api is trying to WakeUp your car because our integration is just polling data from MySkoda API, not from the car. Only place where wake-up is called is from MySkoda mobile app when you start it (and when wakeup is enabled in settings), and even that will happen max 3x per day

From logs I have noticed you car is requesting auxiliary-heating data even your car probably doesn't have this capability, so I will have a look why its requested, but don't this that's causing this problem

**Comment by smalldatach** [comment]
Hi

Same issue here...
Skoda Enyaq... But i dont think it depends on the car... ;)

**Comment by prvakt** [comment]
fyi looks like MySkoda api is having some issues today

**Comment by SamA699** [comment]
I also have a Citigo eIV with the same error result in homeassistant.
I waited 24 hours ... still the same .... the Skoda-App shows "Nicht verfügbar", so it may be a skoda-server problem!?

**Comment by thomasgodon** [comment]
I also have this since a few hours, but the my skoda app is also not working, seems like the api is down/malfunctioning in general atm :)

**Comment by prvakt** [comment]
@Dedier: would it be possible to generate diagnostics report from your car when MySkoda is back online? I'm just wondering why auxiliary-heating data was requested for your car because I'm guessing your car doesn't have this capability

**Comment by zipposi** [comment]
I also have Citygo IV

**Comment by zipposi** [comment]
Waiting 2 days, still is a problem.. The application (also closed for 2 days) still works OK, just the integration doesn't work.

Please advise.

**Comment by prvakt** [comment]
until this problem get fixed, please use [v1.16.1](https://github.com/skodaconnect/homeassistant-myskoda/releases/tag/v1.16.1) 

we have introduced departure timers in v1.17.x which CitigoE iV doesn't like and unfortunately it breaks the update logic completely

**Comment by zipposi** [comment]
Just to notify that 1.16.1 works perfectly.

Thank you and merry christmas and a happy new year!

**Comment by zipposi** [comment]
well, not perfectly, I was too fast :)

There are only 5 entities shown, but should be much more. Any ideas..?

**Comment by zipposi** [comment]
I checked the log and there is a new error

```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:112
First occurred: 19:02:33 (1 occurrences)
Last logged: 19:02:33

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 70, in on_connected
    await self.on_connected_event.data_event(None)
  File "/usr/local/lib/python3.13/site-packages/pymammotion/event/event.py", line 63, in data_event
    await self.on_data_event()
  File "/usr/local/lib/python3.13/site-packages/pymammotion/event/event.py", line 18, in __call__
    await asyncio.gather(*[handler(*args, **kwargs) for handler in self.__eventhandlers])
  File "/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 201, in on_connect
    await self._ble_sync()
  File "/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 222, in _ble_sync
    await loop.run_in_executor(None, self._mqtt.send_command, self.iot_id, command_bytes)
  File "/usr/local/lib/python3.1
3/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 66, in send_command
    self._mqtt_client.get_cloud_client().send_cloud_command(iot_id, command)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pymammotion/aliyun/cloud_gateway.py", line 697, in send_cloud_command
    raise DeviceOfflineException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.DeviceOfflineException: 6205

```

**Comment by WebSpider** [comment]
> well, not perfectly, I was too fast :)
> 
> There are only 5 entities shown, but should be much more. Any ideas..?

Which entities are shown, and which are not shown?

**Comment by WebSpider** [comment]
We're reworking the integration setup, so that we only initially request the bare minimum from MySkoda to get going. This should at least let the integration startup, at which point your diagnostics and logfiles are a lot more useful :)

**Comment by prvakt** [comment]
fixed in [v1.18.1](https://github.com/skodaconnect/homeassistant-myskoda/releases/tag/v1.18.1)
