### ISSUE TITLE
bad capability configuration for all entitys

### ISSUE THREAD

**Issue by ebcjaa** [skodaconnect/homeassistant-myskoda#49]
After upgrade to 1.4.2  all entity's are  in state "not provided". my car is Enyaq 85x
Log file: 
[home-assistant_2024-09-29T15-09-07.722Z.log](https://github.com/user-attachments/files/17179856/home-assistant_2024-09-29T15-09-07.722Z.log)
In the log file I can see that the skoda server is reporting  "INSUFFICIENT_BATTERY_LEVEL" for almost all capabillities.... 
But should that stop the integration?   
myskoda app is working but after a while show the "battery protection message". the car shows no alerts, 12v battery voltage is 13.2v...

**Comment by dvx76** [comment]
We can only guess how the application is implemented. Our assumption is that if a capability has any status then the endpoints related to that capability will fail and should not be attempted.

> myskoda app is working but after a while show the "battery protection message"

But does it actually work? It might just be showing the last known values but not fetching anything new.

Either way we should definitely improve the logging around this. Example for reference:

```
2024-09-29 17:08:33.493 ERROR (MainThread) [homeassistant.components.switch] Error adding entity switch.charging for domain switch with platform myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1670, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/myskoda/switch.py", line 190, in is_on
    return self._status().state == ChargingState.CHARGING
           ^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/switch.py", line 113, in _status
    status = self._charging().status
             ^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/switch.py", line 98, in _charging
    raise InvalidCapabilityConfigurationError(
custom_components.myskoda.utils.InvalidCapabilityConfigurationError: Entity 'charging' has a bad capability configuration for vehicle 'Enyaq Engine(type='iV', power=210, capacity_in_liters=None) 2024 (5AZJK4)'.
```

No need to dump a complete traceback. We can catch `InvalidCapabilityConfigurationError`, log an info, or warning at best, and move on.

**Comment by WebSpider** [comment]
Batteryprotection is one we also ran across in the old integration.

Its related to protection of the 12v battery due to battery draw of the modem thats used for api interaction. The exact limits i think TheFarFar knows.

**Comment by WebSpider** [comment]
> No need to dump a complete traceback. We can catch `InvalidCapabilityConfigurationError`, log an info, or warning at best, and move on.

We should mark the related Entity as outdated in some form as well. Maybe an `Unknown` state?
