### ISSUE TITLE
MissingField: Field "service_partner" of type ServicePartner is missing in Info instance

### ISSUE THREAD

**Issue by TimMeadows** [skodaconnect/homeassistant-myskoda#50]
Hi, 

Another one I'm afraid - when installing the integration. 

I added a service partner in the Skoda app, and then it started working. 

Thanks

Tim

Logger: custom_components.myskoda.coordinator
Source: helpers/update_coordinator.py:354
integration: MySkoda ([documentation](https://github.com/skodaconnect/homeassistant-myskoda/blob/main/README.md), [issues](https://github.com/skodaconnect/homeassistant-myskoda/issues))
First occurred: 17:53:41 (4 occurrences)
Last logged: 17:54:27

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 203, in get_vehicle
    info = await self.get_info(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 159, in get_info
    return await self.rest_api.get_info(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 52, in get_info
    return await self._make_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 38, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "service_partner" of type ServicePartner is missing in Info instance

**Comment by WebSpider** [comment]
This has been fixed and will be released in the next version.

**Comment by WebSpider** [comment]
This has been released with v1.4.3, please provide your feedback if there is any issue remaining, thanks!
