### ISSUE TITLE
Field "car_type" of type EngineType in DrivingRange has invalid value 'hybrid'

### ISSUE THREAD

**Issue by Tokotor** [skodaconnect/homeassistant-myskoda#65]
When i want to connect to my car. Octavia IV phev from 2021 i get the following message.

Logger: myskoda.rest_api
Bron: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:43
Eerst voorgekomen: 09:48:25 (2 gebeurtenissen)
Laatst gelogd: 09:48:34

Failed to load data from url /v2/vehicle-status/TMBJW9NX9MY131058/driving-range. Return value was '{"carType":"hybrid","totalRangeInKm":163,"primaryEngineRange":{"engineType":"gasoline","currentSoCInPercent":23,"currentFuelLevelInPercent":23,"remainingRangeInKm":130},"secondaryEngineRange":{"engineType":"electric","currentSoCInPercent":74,"remainingRangeInKm":33},"carCapturedTimestamp":"2024-10-03T05:44:58Z"}'
Traceback (most recent call last):
  File "<string>", line 16, in __mashumaro_from_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'hybrid' is not a valid EngineType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "car_type" of type EngineType in DrivingRange has invalid value 'hybrid'

**Comment by Tokotor** [comment]
I see someone else already reported this.
