### ISSUE TITLE
ValueError: Sensor sensor.skoda_enyaq_charging_state provides state value 'none', which is not in the list of options provided

### ISSUE THREAD

**Issue by sonar98** [skodaconnect/homeassistant-myskoda#72]
In version 1.4.5 following error is logged.

````
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:724
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 11:47:49 (1 gebeurtenissen)
Laatst gelogd: 11:47:49

myskoda: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 571, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 636, in state
    raise ValueError(
ValueError: Sensor sensor.skoda_enyaq_charging_state provides state value 'none', which is not in the list of options provided

**Comment by dvx76** [comment]
Reopen as per https://github.com/skodaconnect/homeassistant-myskoda/pull/80#issuecomment-2416224388

**Comment by dvx76** [comment]
@sonar98 can you please look for additional logs/errors just before what is posted in this issue. Potentially something like `"Failed to load data from url %s. Return value was '%s'"`.

And/or enable tracing in the integration and provide the raw API response from the charging endpoint.

**Comment by sonar98** [comment]
This is in my log:

``
2024-10-16 12:02:11.215 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/charging/TMB - response: 200 (615 bytes) {"isVehicleInSavedLocation":false,"status":{"chargingRateInKilometersPerHour":0.0,"chargePowerInKw":0.0,"remainingTimeToFullyChargedInMinutes":0,"battery":{"remainingCruisingRangeInMeters":237000,"stateOfChargeInPercent":62}},"settings":{"targetStateOfChargeInPercent":80,"preferredChargeMode":"MANUAL","availableChargeModes":["MANUAL"],"chargingCareMode":"ACTIVATED","autoUnlockPlugWhenCharged":"OFF","maxChargeCurrentAc":"MAXIMUM","batterySupport":"ENABLED"},"carCapturedTimestamp":"2024-10-15T15:08:20Z","errors":[{"type":"STATUS_OF_CHARGING_NOT_AVAILABLE","description":"Status of charging is not available."}]}
2024-10-16 12:02:11.584 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 7.681 seconds (success: True)
2024-10-16 12:02:11.585 ERROR (MainThread) [homeassistant.components.sensor] myskoda: Error on device update!
Traceback (most recent call last):
``

**Comment by WebSpider** [comment]
OK, so the state is actually not available from the API, and the API knows about it, as indicated by the `errors` field.
In this case, `None` should be made a valid state, since we actually know that this is missing.
The result of this will be that the sensor will go to `Unavailable` until we get a reply back again from Skoda including a valid value.
