### ISSUE TITLE
Issue when initializing the plugin after update to 1.4.5

### ISSUE THREAD

**Issue by arjanvroege** [skodaconnect/homeassistant-myskoda#74]
**Describe the bug**
Updated the plugin tot 1.4.5. and after a reboot of HA the integration is not able to initialize due to the following error.

**Latest working release**
1.4.2 was working but had some other issues ;-)

**Debug logs**
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 14:55:34 (1 occurrences)
Last logged: 14:55:34

Error setting up entry arjanvroege@hotmail.com for myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/__init__.py", line 55, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2108, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 3 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/myskoda/device_tracker.py", line 3, in <module>
    from homeassistant.components.device_tracker.config_entry import (
ImportError: cannot import name 'TrackerEntityDescription' from 'homeassistant.components.device_tracker.config_entry' (/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py)

**Installation:**
 - Home Assistant variant: HassOS

**Comment by WebSpider** [comment]
What version HA are you running?

**Comment by arjanvroege** [comment]
2024.9.3

**Comment by WebSpider** [comment]
Ah yes. We are using a new way of addressing the device tracker, based on https://developers.home-assistant.io/docs/core/entity/device-tracker#trackerentity
This requires a minimal of HA [2024.10.0](https://github.com/home-assistant/core/releases/tag/2024.10.0)

I will update the minimal version of HA to run this integration.
