### ISSUE TITLE
the custum integration wont start

### ISSUE THREAD

**Issue by Thomsen-79** [skodaconnect/homeassistant-myskoda#92]
hi trying to use the skodaconnect/homeassistant-myskoda but it will not start up. getting a error in log as shown here(i have removed some of my email and phone number): 
Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 18, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'PHONE' is not a valid CommunicationChannel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "<string>", line 20, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "preferred_channel" of type Optional[CommunicationChannel] in PredictiveMaintenanceSettings has invalid value 'PHONE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "setting" of type PredictiveMaintenanceSettings in PredictiveMaintenance has invalid value {'serviceActivated': True, 'preferredChannel': 'PHONE', 'email': 'Thomsen***@*****', 'phone': '+45317*****'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 230, in get_vehicle
    maintenance = await self.get_maintenance(vin)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 213, in get_maintenance
    return await self.rest_api.get_maintenance(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 91, in get_maintenance
    return await self._make_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 42, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "predictive_maintenance" of type Optional[PredictiveMaintenance] in Maintenance has invalid value {'setting': {'serviceActivated': True, 'preferredChannel': 'PHONE', 'email': 'Thomsen***@*******', 'phone': '+45317*****'}}

How i installed it:
added as a custom repositories in hacs and installed it. restarted home assistant and added the integration by typing in my email and password as requested

**Comment by WebSpider** [comment]
Thanks for this report. This is a car configuration we have not yet ran into and will add support for this in the next version.
